# Generated by Django 4.2.28 on 2026-02-12

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtGalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('image', models.ImageField(upload_to=core.models.generate_unique_filename, verbose_name='Rasm')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('author_full_name', models.CharField(max_length=255, verbose_name='Ism familiya')),
                ('text', models.TextField(verbose_name='Matn')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Art galereya elementi',
                'verbose_name_plural': 'Art galereya',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollaborationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('name', models.CharField(max_length=255, verbose_name='Loyiha nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('date', models.DateField(verbose_name='Sana')),
                ('status', models.CharField(choices=[('planned', 'Rejalashtirilmoqda'), ('ongoing', 'Davom etmoqda'), ('completed', 'Yakunlangan')], default='planned', max_length=20, verbose_name='Holati')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Hamkorlik loyihasi',
                'verbose_name_plural': 'Hamkorlik loyihalari',
                'ordering': ['-date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ForeignPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('organization_name', models.CharField(max_length=255, verbose_name='Tashkilot nomi')),
                ('country', models.CharField(max_length=150, verbose_name='Mamlakat')),
                ('short_info', models.TextField(verbose_name="Qisqacha ma'lumot")),
                ('image', models.ImageField(upload_to=core.models.generate_unique_filename, verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Xorijiy hamkor',
                'verbose_name_plural': 'Xorijiy hamkorlar',
                'ordering': ['order', 'organization_name'],
            },
        ),
        migrations.CreateModel(
            name='InternationalRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(default="Xalqaro aloqalar to'g'risida", max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Xalqaro aloqalar',
                'verbose_name_plural': 'Xalqaro aloqalar',
            },
        ),
        migrations.CreateModel(
            name='InternationalVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha')),
                ('video_url', models.URLField(verbose_name='Video havola')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('international_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.internationalrelation', verbose_name='Xalqaro aloqalar')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': "Video to'plami",
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternationalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('image', models.ImageField(upload_to=core.models.generate_unique_filename, verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('international_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.internationalrelation', verbose_name='Xalqaro aloqalar')),
            ],
            options={
                'verbose_name': 'Fotosurat',
                'verbose_name_plural': 'Fotosuratlar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('image', models.ImageField(upload_to=core.models.generate_unique_filename, verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('art_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.artgalleryitem', verbose_name='Art galereya elementi')),
            ],
            options={
                'verbose_name': 'Art galereya rasmi',
                'verbose_name_plural': 'Art galereya rasmlari',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
